#!/usr/bin/env python3

import colors as c

print(c.clear + c.yellow + 'Who would cross the Bridge of Death must answer me these questions three. Ere the    other side he see.')

def prompt(question):
    print(question)
    answer = input('> ' + c.magenta).lower().strip()
    print(c.reset)
    return answer

def live():
    print(c.green + 'Right, off you go then.')
    
def die():
    print(c.red + 'Thou art cast into the Gorge of Eternal Peril')

name = prompt(c.green + 'What is your name?')

quest = prompt(c.green + 'What is your quest?')

if name == 'lancelot' or name == 'galahad':
    color = prompt(c.green + 'what is your favourite colour?')
    if color == 'blue':
        live()
    else:
        die()

elif name == 'robin':
    capital = prompt(c.green + 'What is the capital of Assyria')
    if capital in ['assur','ashur']:
        live()
    else:
        die()

if name == 'king arthur':
    speed = prompt(c.green + 'What is the air speed velocity of an unladen swallow?')
    if speed == '24 mph':
        live()
    else:
        die()
