#!/usr/bin/env python3

import colors as c

import random as r

print(c.clear + c.magenta + 'Welcome to the magic eight ball!')
print(c.magenta + 'Please type your question below:')

answers = ['yes',
'no' ,
'maybe' ,
'definately' ,
'my soarces say no' ,
'without a doubt' ,
'you really dont want to know' ,
':|' ,
':@ NO WAY' ,
':P lol' ,
':D good question ask again' ,
'( ͡° ͜ʖ ͡°) my name is lenny face and I like trains' ,
' ¯\_(ツ)_/¯ I dont know' ,
'ಠ_ಠ thats a no brainer and the answer is no']

try:

    while True:
        question = input(c.red + '> ' + c.green + ' ')

        if 'Brooke' in question:
            print(c.red + 'ಠ_ಠ no way' + c.x)

        elif 'I' in question:
            print(c.green + 'definately :D')


        else:
            answer = r.choice(answers)
            print(answer)

except KeyboardInterrupt:
    print(c.orange + '         See Ya :-D  DERPY DERP')
    exit()
