#!/usr/bin/env python3

import colors as c

import random as r

print(c.magenta + 'Welcome to the magic eight ball!')
print(c.magenta + 'Please type your question below:')

answers = ['yes',
'no' ,
'maybe' ,
'get off my lawn' ,
'leave me alone and ask siri' ,
'herobrine is the minecraft god of death' ,
'definately' ,
'my soarces say no' ,
'reply hazy ask again' ,
'stay in the adult state' ,
'surface whats not sand' ,
'ask what else' ,
'you are the boss' ,
'ask again later' ,
'without a doubt' ,
'you really dont want to know' ,
'meh' ,
'eat chocolate and ask again later']

input(c.red + '> ' + c.green + ' ')

answer = random.choice(answers)

print(answer)
