#!/usr/bin/env python3

red = '\033[0;31m'
yellow = '\033[0;33m'
orange = '\033[1;31m'
magenta = '\033[0;35m'
print(orange + 'hello, what is your name?')
name = input(red + '> ' + magenta + ' ')

print(yellow + 'hello, ' + magenta + name)
