#!/usr/bin/env python3

import colors as c

text = '''
You are and soldier and your team members are heading out to war, you go with then. 
you all get in the {army_vehicle} , it blows up in your face, you are the only
survivor. your best friend, {name1} , was killed. you {way_of_moving} to the nearest
cover, the air around you is filled with gunfire. you are hit in the {bod6y_part} .
you scramble out of your cover just before it is hit with an RPG. you look up and see
an enemy with a name tag saying {name2} . the soldier shoots you in the face.
YOUR DEAD.
'''

words = {
    "army_vehacle" : {},
    "name1" : {},
    "way_of_moving" : {},
    "body_part" : {},
    "name2" : {}
    }

print(c.clear + '''
Welcome to madlibs, enter your answers.
''')

answer = {}
for key in words:
    print('would get an answer for ' + key )
