#!/usr/bin/env python3

import colors as c
from utils import ask

text = '''
You are a soldier and your team members are heading out to war, you go with
them. you all get in the {army vehicle} , it blows up in your face, you are the
only survivor. your best friend, {name1} , was killed. you {way of moving} to
the nearest cover, the air around you is filled with gunfire. you are hit in
the {body part} . you scramble out of your cover just before it is hit with an
RPG. you look up and see an enemy with a name tag saying {name2} . the soldier
shoots you in the face.
YOU DEAD.
'''

words = {
    "army vehicle" : None,
    "name1" : None,
    "way of moving" : None,
    "body part" : None,
    "name2" : None,
    }

print(c.clear + '''
Welcome to madlibs, enter your answers.
''')

for keyword in words:
    words[keyword] = ask(keyword.title().rstrip('0123456789') + ': ')

print(c.clear + text.format(**words))
