#!/usr/bin/env python3

import sys
import colors as c

print(c.clear + c.magenta + 'WELCOME' + c.red + ' to' + c.green + ' mtable' + c.reset)

if len(sys.argv) < 2:
    number = input('Please enter a number from 1-12: ')
else:
    number = sys.argv[1]

for count in range(13):
    print(count, 'x', number, '=', int(number) * count)
