#!/usr/bin/env python3

import jurassic as quiz
import colors as c
import random

print(c.clear + quiz.intro)

while quiz.questions:
    question_function = random.choice(quiz.questions)
    is_correct = question_function()
    if is_correct:
        print('you got it right!')
        quiz.questions.remove(question_function)
    else:
        print('shame on you')
