#!/usr/bin/env python3
import colors as c
import random as r
import time as t

while True:
    for count in range (4):
        for count in range (11):
            print(c.green + 'badgers' + c.reset)
            t.sleep(0.5)
        for count in range (2):
            print(c.magenta + 'mushroom' + c.reset)
            t.sleep(0.5)
        print(c.clear)

    for count in range (2):
        print(c.red + 'snaaaaaaaaaaaaaaaaaaaaaaaaaaake' + c.reset)
        t.sleep(0.5)
