#!/usr/bin/env python3

import colors as c
import sys

print(c.clear + 'Welcome to the mtable')

if len(sys.argv) < 2:
    number = input('Please pick a number from 1-12 ')
else:
   number = sys.argv[1]

for count in range(13):
    print(count, 'x', number, '=', int(number) * count)
