#!/usr/bin/env python3

import colors as c
import random as r

print(c.clear + 'Do you like waffles?')
answer = input(' ')

if answer == 'yes':
    print('I like waffles')

else:
    print('Well I like waffles')

print('Do you like pancakes?')
answer = input(' ')

if answer == 'yes':
    print('I like pancakes')

else:
    print('Well I like pancakes')

print('Do you like french toast?')
answer = input(' ')

if answer == 'yes':
    print('I like french toast')

else:
    print('Well I like french toast')
